/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

import com.rpst.yc.database.DatatypeUserRegistration;
import com.rpst.yc.database.JDBCConnection;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.FileDialog;
import java.awt.Image;
import java.awt.Label;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author sanjib
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Registration = new javax.swing.JButton();
        txt_phone = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_userid = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        pw_confirmpassword = new javax.swing.JPasswordField();
        pw_password = new javax.swing.JPasswordField();
        cbo_usertype = new javax.swing.JComboBox();
        pnl_image = new javax.swing.JPanel();
        btn_chooseimage = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Full Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tunga", 2, 14)); // NOI18N
        jLabel2.setText("Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("User ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Phone");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ID Type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

        btn_Registration.setText("Register");
        btn_Registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));
        getContentPane().add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 210, 30));
        getContentPane().add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, 30));
        getContentPane().add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));
        getContentPane().add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 210, 30));
        getContentPane().add(txt_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 210, 30));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 210, 30));
        getContentPane().add(pw_confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 210, 30));
        getContentPane().add(pw_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 210, 30));

        cbo_usertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Students", "Others", " " }));
        getContentPane().add(cbo_usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 30));

        pnl_image.setBackground(new java.awt.Color(0, 51, 204));
        pnl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_imageLayout = new javax.swing.GroupLayout(pnl_image);
        pnl_image.setLayout(pnl_imageLayout);
        pnl_imageLayout.setHorizontalGroup(
            pnl_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_imageLayout.setVerticalGroup(
            pnl_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        btn_chooseimage.setText("Choose Image");
        btn_chooseimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooseimageActionPerformed(evt);
            }
        });
        getContentPane().add(btn_chooseimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   DatatypeUserRegistration dataobj=new DatatypeUserRegistration();
   public void input(){
    dataobj.Setfullname(txt_fullname.getText());
    dataobj.setAddress(txt_address.getText());
    dataobj.setPhon(txt_phone.getText());
    dataobj.setAge(txt_age.getText());
    dataobj.setUserid(txt_userid.getText());
    dataobj.setUsertype(cbo_usertype.getSelectedItem().toString());
    dataobj.setUsername(txt_username.getText());
    dataobj.setPassword(pw_password.getPassword().toString());    
}    
    private void btn_RegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrationActionPerformed
        try{
        input();
        JDBCConnection conn=null;
        conn=new JDBCConnection();
        conn.RegistrationUsers(dataobj);
         }
        catch(SQLException ex){
            
        }catch(ClassNotFoundException e){    
        }
    }//GEN-LAST:event_btn_RegistrationActionPerformed
private void Clear(){
    txt_fullname.setText(null);
    txt_address.setText(null);
    txt_phone.setText(null);
    txt_age.setText(null);
    txt_userid.setText(null);
    txt_username.setText(null);
    pw_password.setText(null);
    pw_confirmpassword.setText(null);
}
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        Clear();
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_chooseimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooseimageActionPerformed
        try {
            FileDialog file=new FileDialog(this);
            file.setVisible(true);
            
            System.out.println(file.getFile());
            BufferedImage image=ImageIO.read(new File(file.getFile()));
            JLabel lbl_img=new JLabel(new ImageIcon(image));
            pnl_image.add(lbl_img);
        } catch (IOException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_chooseimageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Registration;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_chooseimage;
    private javax.swing.JComboBox cbo_usertype;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnl_image;
    private javax.swing.JPasswordField pw_confirmpassword;
    private javax.swing.JPasswordField pw_password;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_userid;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
